//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS.WHITE.Repository.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FED_USERS
    {
        public long USER_ID { get; set; }
        public string USER_CAI { get; set; }
        public string USER_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DTM_CRT { get; set; }
        public string USR_CRT { get; set; }
        public System.DateTime DTM_UPD { get; set; }
        public string USR_UPD { get; set; }
    }
}
