//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS.WHITE.Repository.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPM_PARAMETERS
    {
        public long PARAMETER_ID { get; set; }
        public string CATEGORY { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string PARENT_CATEGORY { get; set; }
        public System.DateTime DTM_CRT { get; set; }
        public string USR_CRT { get; set; }
        public System.DateTime DTM_UPD { get; set; }
        public string USR_UPD { get; set; }
    }
}
